### ISSUE TITLE
FileNotFoundError in running "FB5M & FB2M KG to DB" and 2 others

### ISSUE THREAD

**Issue by pyupya** [PetrochukM/Simple-QA-EMNLP-2018#4]
Hi, I'm a student studying in QA with deeplearning.
I'm following your github 'readme' and have some problems.

first, i'm first time in use PostgreSQL, so not sure how I can do thrid dot.
⊙ Create and populate a PostgreSQL table named fb_two_subject_name with notebooks/Simple QA KG to PostgreSQL DB/fb_two_subject_name.csv.gz

second, where I should put the SimpleQuestions v2 dataset?

third, I'm trying to run the "FB5M & FB2M KG to DB", but I got errors. The first one I got was 'FileNotFoundError', and it says I need '.pass', how I can get it or do something?

**Comment by PetrochukM** [comment]
Please reopen this issue if you are still struggling.

**Comment by DbrRoxane** [comment]
@PetrochukM @pyupya I have the same issue and wondered if you have a solution since it is closed?

**Comment by PetrochukM** [comment]
Hello. Can you please be more clear? There are three issues above.

**Comment by DbrRoxane** [comment]
As my colleague, I don't know how to create/generate POSTGRE tables from the CSV given.
Second, when I run the notebook (Simple QA KG to PostgreSQL DB), I have an error because the '.pass' file does not exists and I don't know what it is. 

I have created a data folder with FB2M and FB5M with the path associated to these text files indicated in _utils.py_ FB2M_KG and FB5M_KG

I guess these errors are linked but I don't know how to deal with it. Any idea?

**Comment by PetrochukM** [comment]
1) Please take the time to read up excellent online tutorials by Googling the keywords: "POSTGRE tables CSV"

2) Sorry for not providing enough details on ``.pass``. Please create the ``.pass`` file with these environment variables:
```
DB_NAME=
DB_PORT=
DB_USER=
DB_HOST=
DB_PASS=
```
Specifications:
- DB_NAME – the database name
- DB_USER – user name used to authenticate
- DB_PASS – password used to authenticate
- DB_HOST – database host address
- DB_PORT – connection port number (typically 5432)

**Comment by PetrochukM** [comment]
I updated the README with instructions on creating a ``.pass`` file.

**Comment by pyupya** [comment]
Thanks for answering me. I'm late for reply, but the problem you answered
is what I got.
If I get more problem, I will ask on github or email.
Thanks!

2019년 5월 13일 (월) 오전 4:29, Michael Petrochuk <notifications@github.com>님이 작성:

**Comment by AlxBouras** [comment]
Hi, I’m a research intern working with @DbrRoxane; I have the following questions :


1) You mention in the README to Create and populate a PostgreSQL table named fb_two_subject_name.

From my understanding of this, I should create the table outside of the notebooks with the csv file.
However, I noticed that the table is created in FB2M & FB5M Subject MID to Subject Name, should I be running this file?

2) I’m a bit of a loss for which are the precise steps to run Simple QA End-to-End ?

Should I be running all the files in the Simple QA KG to PostgreSQL DB directory in the notebooks? If so, is there a peculiar order I should run them in?

Are there any more steps to take?


Thanks in advance

**Comment by PetrochukM** [comment]
@Everyone: Sorry, I do not have time these days to support this code base. I will not be answering questions that are otherwise answerable by Google or existing documentation.

-------------------

1) The table is created also in `notebooks/Simple QA KG to PostgreSQL DB/FB2M & FB5M Subject MID to Subject Name.ipynb`. The `fb_two_subject_name.csv.gz` is an export of the table created by that notebook. Unless you want to rerun the notebook, please use the export instead.

2)  - Please run the `notebooks/Simple QA End-to-End` in the order of 1, 2 and 3.
    - No, you do not need to run anything in `Simple QA KG to PostgreSQL DB`. The only usage of PostgreSQL is in `notebooks/Simple QA End-To-End/Step 2 - Generate Candidates.ipynb`. It uses the table ``FB2M_NAME_TABLE``; therefore, you only need ``fb_two_subject_name``. Please read the code for more information.

Based on your questions, I do not think I am providing any more context than the existing instructions in the README. Please take care to follow those before asking further questions.

**Comment by AlxBouras** [comment]
Thanks for the answer and sorry for the inconvenience.
